AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trustworthy Model Registry - Artifact API

Globals:
  Function:
    Runtime: python3.9
    Timeout: 300
    MemorySize: 2400

Parameters:
  ArtifactNameIndexTable:
    Type: String
    Default: ArtifactNameIndex
    Description: DynamoDB table name storing artifact name index entries

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
        AllowHeaders: ['*']

  ArtifactCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/artifact_create/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Events:
        CreateArtifact:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: POST
            Path: /artifact/{artifact_type}
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:HeadObject
            Resource: !Sub "${ArtifactBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ArtifactBucket.Arn
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-ArtifactCreateFunction*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ArtifactNameIndexTable}"
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          ARTIFACT_DOWNLOAD_BASE_URL: !Sub "https://${ArtifactBucket}.s3.${AWS::Region}.amazonaws.com"
          ARTIFACT_NAME_INDEX_TABLE: !Ref ArtifactNameIndexTable
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache

  ArtifactDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/artifact_download/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Events:
        DownloadArtifact:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /download/{id}
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource: !Sub "${ArtifactBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ArtifactBucket.Arn
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ArtifactNameIndexTable}"
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          ARTIFACT_DOWNLOAD_BASE_URL: !Sub "https://${ArtifactBucket}.s3.${AWS::Region}.amazonaws.com"
          ARTIFACT_NAME_INDEX_TABLE: !Ref ArtifactNameIndexTable
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache

  ArtifactRetrieveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/artifact_get/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource: !Sub "${ArtifactBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ArtifactNameIndexTable}"
      Events:
        RetrieveArtifact:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /artifacts/{artifact_type}/{id}
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          ARTIFACT_NAME_INDEX_TABLE: !Ref ArtifactNameIndexTable
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache

  ArtifactRegexSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/artifact_regex/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Events:
        RegexSearch:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: POST
            Path: /artifact/byRegEx
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:HeadObject
            Resource: !Sub "${ArtifactBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ArtifactNameIndexTable}"
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          ARTIFACT_NAME_INDEX_TABLE: !Ref ArtifactNameIndexTable
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache

  ArtifactUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/artifact_update/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:HeadObject
            Resource: !Sub "${ArtifactBucket.Arn}/*"
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !GetAtt ArtifactBucket.Arn
      Events:
        UpdateArtifact:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: PUT
            Path: /artifacts/{artifact_type}/{id}
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache
  ArtifactResetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: backend/src/handlers/reset/app.lambda_handler
      EphemeralStorage:
        Size: 10240
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !Sub "${ArtifactBucket.Arn}"
              - !Sub "${ArtifactBucket.Arn}/*"
      Events:
        ResetRegistry:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: DELETE
            Path: /reset
      Environment:
        Variables:
          ARTIFACT_STORAGE_BUCKET: !Ref ArtifactBucket
          ARTIFACT_STORAGE_PREFIX: artifacts
          ARTIFACT_STORAGE_REGION: !Ref AWS::Region
          ARTIFACT_METADATA_PREFIX: metadata
          HF_HOME: /tmp/hf-cache
          HUGGINGFACE_HUB_CACHE: /tmp/hf-cache

Outputs:
  ApiUrl:
    Description: Base URL for testing
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com"
  ArtifactBucketName:
    Description: S3 bucket storing uploaded artifacts
    Value: !Ref ArtifactBucket
